#!/usr/bin/env bash

set -euo pipefail

# Ensure DOTLY_PATH is set
export DOTLY_PATH="${DOTLY_PATH:-/home/pazthor/IdeaProjects/dat}"
source "$DOTLY_PATH/scripts/core/_main.sh"

##? lista los monitoresocn su respectivas confs 
##?
##? Usage:
##?    comandos [options]
##?
docs::parse "$@"



niri msg outputs
